spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: book-service-update

server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true