server:
  port: 8086

spring:
  application:
    name: store-book-service
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    function:
      definition: acceptBook
    stream:
      bindings:
        acceptBook-in-0:
          destination: check-book-channel
    bus:
      id: store-book-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true