server:
  port: 8082

spring:
  application:
    name: client-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      discovery:
        enabled: true
        service-id: config-server
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    preferIpAddress: true
    appname: client-service

book-service:
  url: http://localhost:8083
  ribbon:
    eureka:
      enabled: false
    ServerListRefreshInterval: 1000

