server:
  port: 8084

spring:
  application:
    name: creation-book-service
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    function:
      definition: sendBook
    stream:
      bindings:
        sendBook-out-0:
          destination: create-book-channel
    bus:
      id: creation-book-service
  integration:
    poller:
      fixed-delay: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true