spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: book-service
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true