spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  shouldUseDns: true
  server:
    expected-client-renewal-interval-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    registerWithEureka: false
    fetchRegistry: false
    log-delta-diff: false
    eureka-server-connect-timeout-seconds: 60
    eureka-service-url-poll-interval-seconds: 15
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true

  instance:
    hostname: my-eureka-server.com
    lease-expiration-duration-in-seconds: 70
    metadata-map:
      zone: http://${eureka.instance.hostname}:${server.port}/eureka