spring:
  application:
    name: eureka-server
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

server:
  port: 8761

eureka:
  shouldUseDns: true
  server:
    expected-client-renewal-interval-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
    log-delta-diff: false
    eureka-server-connect-timeout-seconds: 60
    eureka-service-url-poll-interval-seconds: 15
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true

  instance:
    hostname: my-eureka-server.com
    lease-expiration-duration-in-seconds: 70
    metadata-map:
      zone: http://localhost:8761/eureka/